trigger:
- main    # Change to your branch name if needed

variables:
  TF_VERSION: '1.8.5'
  SERVICE_CONNECTION: 'azure-connection-tf'   # ✅ Replace with your Azure Service Connection name
  TF_WORKING_DIR: 'terraform'                 # Folder in your repo containing .tf files
  STORAGE_ACCOUNT_NAME: 'yourtfstateaccount'  # Optional (if backend configured)
  CONTAINER_NAME: 'tfstate'                   # Optional
  STATE_FILE_NAME: 'terraform.tfstate'

stages:
# ==========================================
# Stage 1: Terraform Init & Validate
# ==========================================
- stage: InitValidate
  displayName: 'Terraform Init & Validate'
  jobs:
  - job: InitValidate
    displayName: 'Initialize and Validate Terraform'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: TerraformInstaller@1
        displayName: 'Install Terraform $(TF_VERSION)'
        inputs:
          terraformVersion: $(TF_VERSION)

      - task: TerraformTaskV4@4
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(TF_WORKING_DIR)'
          backendServiceArm: '$(SERVICE_CONNECTION)'

      - task: TerraformTaskV4@4
        displayName: 'Terraform Validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: '$(TF_WORKING_DIR)'

# ==========================================
# Stage 2: Terraform Plan
# ==========================================
- stage: Plan
  displayName: 'Terraform Plan'
  dependsOn: InitValidate
  jobs:
  - job: Plan
    displayName: 'Generate Terraform Plan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: TerraformInstaller@1
        displayName: 'Install Terraform $(TF_VERSION)'
        inputs:
          terraformVersion: $(TF_VERSION)

      - task: TerraformTaskV4@4
        displayName: 'Terraform Plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(TF_WORKING_DIR)'
          environmentServiceNameAzureRM: '$(SERVICE_CONNECTION)'
          commandOptions: '-out=tfplan'

      # Publish plan as artifact
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(TF_WORKING_DIR)'
          artifact: 'tfplan'

# ==========================================
# Stage 3: Manual Approval
# ==========================================
- stage: Manual_Approval
  displayName: 'Manual Approval before Apply'
  dependsOn: Plan
  jobs:
  - job: WaitForApproval
    displayName: 'Await Manual Approval'
    agent: none        # ✅ FIXED — run on Azure DevOps server, not agent
    steps:
      - task: ManualValidation@0
        displayName: 'Manual Approval Step'
        inputs:
          instructions: 'Please review the Terraform Plan and approve to deploy.'
          onTimeout: 'reject'
          timeout: '72:00:00'

# ==========================================
# Stage 4: Terraform Apply (Deployment)
# ==========================================
- stage: Apply
  displayName: 'Terraform Apply (Deploy Infrastructure)'
  dependsOn: Manual_Approval
  condition: succeeded()
  jobs:
  - job: Apply
    displayName: 'Terraform Apply'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self

      - task: DownloadPipelineArtifact@2
        inputs:
          artifact: 'tfplan'
          path: '$(Pipeline.Workspace)/tfplan'

      - task: TerraformInstaller@1
        displayName: 'Install Terraform $(TF_VERSION)'
        inputs:
          terraformVersion: $(TF_VERSION)

      - task: TerraformTaskV4@4
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(TF_WORKING_DIR)'
          environmentServiceNameAzureRM: '$(SERVICE_CONNECTION)'
          commandOptions: '-auto-approve'
